apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: taloshelp.dev
      http:
        paths:
          - path: /licensing/latest/?(.*)
            pathType: Prefix
            backend:
              service:
                name: licensing-srv
                port:
                  number: 3000
          - path: /features/latest/?(.*)
            pathType: Prefix
            backend:
              service:
                name: features-srv
                port:
                  number: 3000
          - path: /actions/latest/?(.*)
            pathType: Prefix
            backend:
              service:
                name: actions-srv
                port:
                  number: 3000
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: client-srv
                port:
                  number: 3000
